apiVersion: v1
kind: Pod
metadata:
  name: kaniko-backup-storage
  namespace: holm
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--dockerfile=/workspace/Dockerfile"
    - "--context=/workspace"
    - "--destination=10.110.67.87:5000/backup-storage:latest"
    - "--insecure"
    - "--skip-tls-verify"
    volumeMounts:
    - name: build-context
      mountPath: /workspace
  restartPolicy: Never
  volumes:
  - name: build-context
    hostPath:
      path: /tmp/backup-storage
      type: Directory
