apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deploy-controller
  namespace: holm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: deploy.holm.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: deploy-controller
            port:
              number: 80
